---
- name: Copy nginx conf
  template:
    src: "{{ item }}"
    dest: "/opt/bg-frontend/nginx/conf.d/{{ item | basename | regex_replace('\\.j2') }}"
    mode: 0755
  with_fileglob:
    - "templates/front*.j2"
  register: nginx_config

#- name: restart nginx if config has changed
#  service:
#    name: nginx
#    state: reloaded
#  when: nginx_config.changed

#- name: delete default config
#  file:
#    path: /etc/nginx/conf.d/default.conf
#    state: absent

